### ISSUE TITLE
Retour d'état variation pour 0 672 27 - Variateurs récepteurs radio sans neutre 

### ISSUE THREAD

**Issue by Didier3L** [apages2/pluginjeedom-myhome#1]
Le retour d'état (statusnum) du pourcentage de la variation  (SLIDER) ne fonctionne pas.
Quelque soit la valeur du SLIDER (de 1 à 10) le retour d'état est à 100%
https://www.jeedom.com/forum/viewtopic.php?f=28&t=9233&start=260#p399660
https://www.jeedom.com/forum/download/file.php?id=31110

**Comment by apages2** [comment]
Le problème devrait etre résolue en V1.103
