### ISSUE TITLE
Template Management - Commande management

### ISSUE THREAD

**Issue by Didier3L** [apages2/pluginjeedom-myhome#2]
Est il possible de mettre le nom des commandes en Français ?

La commande Get Number of Network Product   `*#13**67##`
Retourne `*#13**67*c##`

**Comment by apages2** [comment]
La traduction est ok.

Par contre quand je lance la commande`  *#13**67##  `sur mon réseau, j'ai en retour  `*#13**67*4## `

Ce qui correspond bien a mes 4 équipements Zigbee.

As-tu encore le problème ?

**Comment by apages2** [comment]
je cloture cet issue car la valeur retournée est en hexadecimal

Exemple : *#13**67*d## pour un réseau composé de 13 équipements
