### ISSUE TITLE
Information Port socket interne et Vitesse du port

### ISSUE THREAD

**Issue by Didier3L** [apages2/pluginjeedom-myhome#4]
La configuration du plugin préconise le port socket interne 55004
et une vitesse du port à 19200
Il serait intéressant de l'indiquer clairement dans la page de configuration comme suit :

**Vitesse du port par défaut 19200
Port socket interne par défaut 55004 (modification dangereuse : entrer la même valeur sur tous les Jeedom déportés avec Myhome)**

**Comment by apages2** [comment]
Ces informations sont présent dans la doc en ligne.

La doc n'est pas disponible dans le plugin directement. Elle le sera en V3 du core Jeedom. Bug connu par l'equipe jeedom
