### ISSUE TITLE
Intérogation à répétition sur des équipements non variateur

### ISSUE THREAD

**Issue by Didier3L** [apages2/pluginjeedom-myhome#5]
A réception d'une trame
> *1 *1

Le plugin interroge les équipements pour obtenir la valeur **SLIDER**.
Mais les équipement sans variation ne retourne pas de valeurs.
Du coup, le plugin interroge sans cesse les équipements sans variation ce qui créé une latence dans le retour d'état des lumières.
Solution proposée :  
interroger uniquement les équipements avec variation.
Ils sont identifiables par le template. ?

**Comment by apages2** [comment]
Probleme corrigé dans la prochaine version
